{
 "title": "Teleoperation information",
 "time": { "from": "2025-03-25T13:54:34.023Z", "to": "2025-03-25T13:55:42.839Z" },
 "panels": [
  { "title": "GPS DATA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"velocidad_resultante\") as velocidad\nFROM \"gps_info\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gps_info",
     "query": "SELECT last(\"latitud\") as lat, last(\"longitud\") as long\nFROM \"gps_info\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "latitud" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"aceleracion_resultante\") as aceleracion\nFROM \"gps_info\" \nWHERE $timeFilter \nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "STREAM METRICS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT last(\"latency\") as latency \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "query": "SELECT last(\"jitter\") as latency \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "targets": [
    {
     "query": "SELECT last(\"bitrate\") as bitrate \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "targets": [
    {
     "query": "SELECT last(\"fps\") as fps \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"latency\") as latency \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"jitter\") as latency \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Bitrate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"bitrate\") as bitrate \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "FPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"fps\") as fps \nFROM \"metrics\" \nWHERE $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  }
 ]
}